@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION ENABLEEXTENSIONS
SET ME=%~n0
SET PARENT=%~dp0

MKDIR temp
COPY *.swf temp

CALL EXTRACT
CALL SCALE
CALL REPLACE

COPY %parent%temp\*.hack.swf %parent%
REM RD /s /q temp